#!/bin/bash
#PBS -N filter_samples
#PBS -l select=1:ncpus=12:mem=128gb
#PBS -l walltime=24:00:00
#PBS -o logs/filtering_out.log
#PBS -e logs/filtering_err.log
#PBS -m abe

############################################
### Sample filtering and doublet removal ###
############################################

set -euo pipefail

project_root="${HOME}/Thema_R"

cd "$project_root"

eval "$(conda shell.bash hook)"
conda activate thema_r_env

Rscript src/01_filter_samples.R
