#!/bin/bash
#PBS -N annotation
#PBS -l select=1:ncpus=12:mem=128gb
#PBS -l walltime=16:00:00
#PBS -o logs/annotation_out.log
#PBS -e logs/annotation_err.log
#PBS -m abe

###############################################
### Cluster marker review and final labels ###
###############################################

set -euo pipefail

project_root="${HOME}/Thema_R"

cd "$project_root"

eval "$(conda shell.bash hook)"
conda activate thema_r_env

Rscript src/04_annotation.R
