#!/bin/bash
#PBS -N dlf_func_analysis
#PBS -l select=1:ncpus=4:mem=64gb
#PBS -l walltime=04:00:00
#PBS -o /data/home/alessandro.digilio/Thema_R/logs/functional_analysis_HA_enriched_destructive_lining_fibroblast_states_out.log
#PBS -e /data/home/alessandro.digilio/Thema_R/logs/functional_analysis_HA_enriched_destructive_lining_fibroblast_states_err.log
#PBS -m abe
#PBS -M alessandro.digilio@policlinico.mi.it

set -euo pipefail

PROJECT_ROOT="/data/home/alessandro.digilio/Thema_R"

cd "$PROJECT_ROOT"

source /data/apps/anaconda/2024.10.01/etc/profile.d/conda.sh
eval "$(conda shell.bash hook)"
conda activate scatac_gex_env

Rscript src/24_GEX_functional_analysis_HA_enriched_destructive_lining_fibroblast_states.R
