#!/bin/bash
#PBS -N macro_subcl
#PBS -l select=1:ncpus=8:mem=96gb
#PBS -l walltime=12:00:00
#PBS -o logs/macrophage_subclustering_out.log
#PBS -e logs/macrophage_subclustering_err.log
#PBS -m abe

################################
### Macrophage subclustering ###
################################

set -euo pipefail

project_root="${HOME}/Thema_R"

cd "$project_root"

eval "$(conda shell.bash hook)"
conda activate scatac_gex_env

Rscript src/macrophage_subclusters/00_subclustering.R
