#!/bin/bash
#PBS -N scrnaseq_THEMA_all
#PBS -l select=1:ncpus=28:mem=375gb
#PBS -l walltime=24:00:00
#PBS -o logs/00_nfcore_scrnaseq_cellranger_all_samples.out
#PBS -e logs/00_nfcore_scrnaseq_cellranger_all_samples.err

#############################################################
### NF-core alignment and quantification with Cell Ranger ###
#############################################################

# run nf-core/scrnaseq with Cell Ranger for the full cohort
set -euo pipefail

# load conda with Nextflow env
eval "$(conda shell.bash hook)"
conda activate nextflow_env # not part of env in "env/" folder

# repository containing the tracked samplesheet and downstream analysis scripts
repo_dir="${HOME}/Thema_R"

# wd for the nf-core/scrnaseq run
run_dir="${HOME}/nfcore_runs/HA_scRNA_membrane"

# Samplesheet with all FASTQ files from the full cohort
samplesheet="${repo_dir}/metadata/samplesheets/scRNA_samplesheet_all_samples.csv"

# directories
outdir="${run_dir}/results"
work_dir="${run_dir}/work"
# singularity cache directory
export NXF_SINGULARITY_CACHEDIR="${work_dir}/singularity_cache"

# reference genome used for alignment and gene quantification
fasta="${run_dir}/ref/gencode/GRCh38.primary_assembly.genome.fa"
gtf="${run_dir}/ref/gencode/gencode.v46.annotation.gtf.gz"

# create directories required by Nextflow
mkdir -p "${outdir}" "${work_dir}" "${NXF_SINGULARITY_CACHEDIR}"
cd "${run_dir}"

# run nf-core/scrnaseq with Cell Ranger on all samples
nextflow run nf-core/scrnaseq \
  -r 4.0.0 \
  -profile singularity \
  -work-dir "${work_dir}" \
  --input "${samplesheet}" \
  --outdir "${outdir}" \
  --genome hg38 \
  --aligner cellranger \
  --fasta "${fasta}" \
  --gtf "${gtf}" \
  --save_align_intermeds true \
  --skip_cellbender true
